db.url=jdbc:h2:~/audiobooks;MODE=PostgreSQL
db.username=sa
db.password=
db.pool.size=20
db.auto.commit=true
file.storage.root=./storage
file.storage.allowed-extensions=jpg,png,jpeg,mp3,ogg,wav,m4b,aac,flac
file.storage.max-size=5242880